name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: {}

concurrency:
  group: ci-build-${{ github.ref }}

permissions:
  contents: read

jobs:
  build-windows:
    name: Build (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.x'
          check-latest: false

      - name: Cache deps and toolchain
        uses: actions/cache@v4
        with:
          path: |
            .deps
            ~/.cache/go-build
            ${{ env:GOPATH }}\pkg\mod
          key: ${{ runner.os }}-deps-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Show Go version
        run: go version
        shell: powershell

      - name: Run Windows build script
        shell: cmd
        run: call .\build.bat

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-windows
          path: |
            build\**
            x86\**
            amd64\**
            arm64\**
          retention-days: 7
